{% set name = "Rx" %}
{% set version = "3.0.1" %}
{% set sha256 = "c7d168618e3cec35fda9c9c8b5d7f966739df4b1a99b315eae1fc2d7d69e2512" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - rx
    - rx.core
    - rx.internal
    - rx.linq
    - rx.linq.observable
    - rx.linq.enumerable
    - rx.concurrency
    - rx.concurrency.mainloopscheduler
    - rx.joins
    - rx.linq.observable.blocking
    - rx.disposables
    - rx.subjects
    - rx.backpressure
    - rx.testing

about:
  home: https://github.com/ReactiveX/RxPY
  license: Apache-2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/apache-2.0.txt'
  summary: 'Reactive Extensions (Rx) for Python'

  # The remaining entries in this section are optional, but recommended
  description: |
    A library for composing asynchronous and event-based programs using
    observable collections and LINQ-style query operators in Python


extra:
  recipe-maintainers:
    - bollwyvl
