{% set name = "Rx" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c7d168618e3cec35fda9c9c8b5d7f966739df4b1a99b315eae1fc2d7d69e2512

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - rx
    - rx.disposable
    - rx.operators
    - rx.scheduler
    - rx.subject
    - rx.testing

about:
  home: https://github.com/ReactiveX/RxPY
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Reactive Extensions (Rx) for Python'
  description: |
    A library for composing asynchronous and event-based programs using
    observable collections and query operator functions in Python

extra:
  recipe-maintainers:
    - bollwyvl
