travis:
  secure:
    BINSTAR_TOKEN: WGycNSRdrXjL4u9Hdrf/FmpbEbAHChoGpUjcTZbXabL4npR+LQ5OemywnPl685KFoW3ANWlm7GGJjmiaZh+qoG85b/319EjuUWAVLnWeF+uJaue3v85Kr3Q33FPgrraEdDq70obZYv4FS43V8WOJSulnHMJxaMnp/uzbz8YLPp6/18JQYYarVJr5t6i5iqwFH78u9dyJRtnqs12NkVfv4ZZkiGZipRiDMh2bskpeI8ueDvMag44rAc1c4Y7XbvHkOz3CnUgY+IJOIe1DGR6Q3wZpeorRfqVitNQ7Xt4KGeF6q+PvFv2dO2Rm1WPZC6a0yJs3aoBam73Cfq6Xn3xAwHFBljuk7TFL6t+/36/hcLj0QV7CuoT/SA6wZHnCZFcyDleKVxPlxK297oRY4uSl0dDsJwC+5WX5omCu7wrDd41wgkIMiBzuFGlr+Y5xHnJJ6wAtnDe+mkCw5Pnlw398bRprf8ygvqdPncISKdPrkLhAm9eDUPs2kCmbC81PRe7hykb2kSP4ywcBoivcYeNUZVyp4JXeAM3qwqoy2YkdGyg2U+RY3ECMOUMkQ8cLtCFEqBE0Zba11m95LKFsQgNLwUkshRILbuhf80GEPatE5sF+SNtoL8q/EkfPZ5j9oLNSaAVkfcbEaMsjsI7agC4R5FJ49mUgK6PmfusUPr1Er0k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
