travis:
  secure:
    BINSTAR_TOKEN: pCbqN0Y+pzZxmo8C0dXJlEMgqR9jT7LyBHYCo1F2/ytZSqZXoxYY+0IZUgF8GFMphpvdLoqHGxkLbPH4w5P9kTPuWxZbkNo5jMyd6gPioN/X7SsT42zkOq65VN3S1v6noC1FzmrsUZQYL3tASlGbOxrfXA4b51rqKk+xnIaSgVp42D9ykCwQ5RICdKNRis3wIgRX9ylJ2FindOD5axx/OlHfD4B3eCI1Osxpi7KQnZ63twEKdcdXPfnijjppWH4vzFpxXfaogr7DPN7QheA3DrKLG30F169igycXmt4b/dosQd/HePhvZVOk9hFAbbovury+bAY7b0PJV27rJTvdEfhFyfvb6cNeSZSNSbZQaBiC05vuU6ko12CXQk/EeSlY9P/6hsQRqzQ4Ouw/RtbTf4GVbyoguvU25OcAo1G6fG+isuVr3bYHj9EeM7/NezhDz4qNKNlYJHHi+h2c7wxUHWBMgUiI1/sspjgk3sIFK/4jXOP2cS9ErFP0BaEWRne652zIxu2efp+mtM/hTQyOn5heTcDbWGL+UJZTREwUpDS/HLMC7vCw4KcQVKRQhewvTjAJCT5lkQlHa8UcHPCbiNVq/qPmlpD4/Mk74xG/OAy8q38Tj64Sx2slcyYAadkXln0vZHXA6rGr4WTxl7/jjKGJr0+odNkB4hu20pTbNVY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
